#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     liftLeftTop,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeftBottom, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorJ,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
 
int motorToRun = 0;
//What motor to run
/*
0 = left lift
*/
 
task main()
{
  while(true)
  {
    while(nNxtButtonPressed == 3)
    {
      if(motorToRun==0)
      {
        motor[liftLeftTop] = 100;
        motor[liftLeftBottom] = 100;
      }
    }
  }
}
