#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     liftLeftBottom, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeftTop,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftRightTop,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     liftRightBottom, tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    latchRight,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    latchLeft,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    intakeLeft,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_6,    intakeRight,          tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Janurary 10th, 2015
Chris: competition day~ put teleop code into a template
*/

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#include "JoystickDriver.c"
#define BOUND(input, min, max) input > max ? max : (input < min ? min : input)
//Bound: takes the input and either returns max (if input is greater than max), min (if input is less than min), or input (if it fits in the range)
void intake()
{
	servo[intakeLeft] = 0;
	servo[intakeRight] = 255;
}
void output()
{
	servo[intakeLeft] = 255;
	servo[intakeRight] = 0;
}
void stopIntake()
{
	servo[intakeLeft] = 127;
	servo[intakeRight] = 127;
}

int threshold=10;
int joyy1;
int joyx2;
int mode = 1;
int liftFakeEncoder = 10;
bool intaking = false;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();
	stopTask(displayDiagnostics);
	eraseDisplay();
	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1) > threshold)
		{
			joyy1 = BOUND(joystick.joy1_y1, -100, 100);
			//joyy1 = joystick.joy1_y1; //We probably don't have to limit the joystick value because we're limiting it when we set the motors
			} else {
			joyy1 = 0;
		}
		if(abs(joystick.joy1_x2) > threshold)
		{
			joyx2 = BOUND(joystick.joy1_x2, -100, 100);
			//joyx2 = joystick.joy1_x2;
			} else {
			joyx2 = 0;
		}

		motor[frontLeft] = BOUND(joyy1 + joyx2, -100, 100) / mode;
		motor[frontRight] = BOUND(joyy1 - joyx2, -100, 100) / mode;
		motor[backLeft] = BOUND(joyy1 + joyx2, -100, 100) / mode;
		motor[backRight] = BOUND(joyy1 - joyx2, -100, 100) / mode;

		if(joy1Btn(1)==1)
		{
			output();
			}	else if(intaking){
			intake();
			} else {
			stopIntake();
		}

		if(joy1Btn(4)==1)
		{
			if(mode==1)
			{
				mode = 6;
				} else {
				mode = 1;
			}
			wait1Msec(250);
		}

		if(joy1Btn(2)==1)
		{
			intaking = !intaking;
			wait1Msec(250);
		}

		if(joy2Btn(6)==1)
		{
			motor[liftLeftTop] = 50;
			motor[liftLeftBottom] = 50;
			motor[liftRightTop] = 70;
			motor[liftRightBottom] = 70;
			} else if(joy2Btn(8)==1) {
			motor[liftLeftTop] = -50;
			motor[liftLeftBottom] = -50;
			motor[liftRightTop] = -70;
			motor[liftRightBottom] = -70;
			} else {
			motor[liftLeftTop] = 0;
			motor[liftLeftBottom] = 0;
			motor[liftRightTop] = 0;
			motor[liftRightBottom] = 0;
		}


		if(joy2Btn(5)==1 && servo[latchLeft] < 200)
		{
			servo[latchRight] = servo[latchRight] - 10;
			servo[latchLeft] = servo[latchLeft] + 10;
			nxtDisplayString(1, "RServo: %3d", servo[latchRight]);
			nxtDisplayString(2, "LServo: %3d", servo[latchLeft]);
			wait1Msec(25);
		}
		if(joy2Btn(7)==1 && servo[latchRight] < 255)
		{
			servo[latchRight] = servo[latchRight] + 10;
			servo[latchLeft] = servo[latchLeft] - 10;
			nxtDisplayString(1, "RServo: %3d", servo[latchRight]);
			nxtDisplayString(2, "LServo: %3d", servo[latchLeft]);
			wait1Msec(25);
		}
	}
}
